server:
  port: 3334

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5334/user_db
    username: user_user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: "this-is-a-very-secret-key-for-jwt-signing-must-be-long-enough-512bits"
    expiration-ms: 86400000  # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html