server:
  port: 3331

spring:
  application:
    name: restaurantService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5331}/${DB_NAME:restaurant_db}
    username: ${DB_USER:restaurant_user}
    password: ${DB_PASSWORD:restaurant_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
