server:
  port: 3333

spring:
  application:
    name: deliveryService
  datasource:
    url: jdbc:postgresql://localhost:5333/delivery_db
    username: delivery_user
    password: delivery_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: delivery-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "orderCreatedEvent:com.deliveryhub.contracts.events.OrderCreatedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html