server:
  port: 3333

spring:
  application:
    name: deliveryService
  datasource:
    url: jdbc:postgresql://localhost:5333/delivery_db
    username: delivery_user
    password: delivery_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html