spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/order_db
    username: order_user
    password: order_pass
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
app:
  restaurant-service:
    url: http://restaurantService:3331